"""
Pydantic schemas for LinkPlace backend.
Contains all request/response validation schemas.
"""

from .user import (
    UserBase,
    UserCreate,
    UserUpdate, 
    UserResponse,
    UserProfile,
    UserListResponse,
    PasswordChange,
    PasswordReset,
    PasswordResetConfirm,
    EmailVerification,
    SocialLoginRequest,
    UserPointsResponse,
    UserStatsResponse,
    UserPreferences,
    UserSearch,
)

from .auth import (
    LoginRequest,
    LoginResponse,
    TokenRefresh,
    TokenResponse,
    SocialLoginResponse,
    RegisterRequest,
    RegisterResponse,
    SocialLoginData,
    OAuth2CallbackRequest,
    LogoutRequest,
    VerifyTokenRequest,
    VerifyTokenResponse,
    ChangeEmailRequest,
    ChangeEmailResponse,
    AccountActivation,
    AccountDeactivation,
    TwoFactorSetup,
    TwoFactorSetupResponse,
    TwoFactorVerify,
    TwoFactorLogin,
    SessionInfo,
    ActiveSessions,
    RevokeSession,
    SecuritySettings,
    SecurityLog,
    SecurityLogs,
    AuthStats,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse", 
    "UserProfile",
    "UserListResponse",
    "PasswordChange",
    "PasswordReset",
    "PasswordResetConfirm",
    "EmailVerification",
    "SocialLoginRequest",
    "UserPointsResponse",
    "UserStatsResponse",
    "UserPreferences",
    "UserSearch",

    # Auth schemas
    "LoginRequest",
    "LoginResponse",
    "TokenRefresh",
    "TokenResponse",
    "SocialLoginResponse",
    "RegisterRequest",
    "RegisterResponse",
    "SocialLoginData",
    "OAuth2CallbackRequest",
    "LogoutRequest",
    "VerifyTokenRequest",
    "VerifyTokenResponse",
    "ChangeEmailRequest",
    "ChangeEmailResponse",
    "AccountActivation",
    "AccountDeactivation",
    "TwoFactorSetup",
    "TwoFactorSetupResponse",
    "TwoFactorVerify",
    "TwoFactorLogin",
    "SessionInfo",
    "ActiveSessions",
    "RevokeSession",
    "SecuritySettings",
    "SecurityLog",
    "SecurityLogs",
    "AuthStats",
]
