version: '3.8'

services:
  # FastAPI 백엔드 서비스
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - DEBUG=True
      - ENVIRONMENT=development
    depends_on:
      - redis
    networks:
      - linkplace-network

  # Redis 서비스 (캐싱 및 세션 스토어용)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - linkplace-network

  # PostgreSQL 데이터베이스 (향후 사용)
  # database:
  #   image: postgres:15
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: linkplace_db
  #     POSTGRES_USER: linkplace
  #     POSTGRES_PASSWORD: linkplace123
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - linkplace-network

  # Nginx (프로덕션 환경용)
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - backend
  #   networks:
  #     - linkplace-network

volumes:
  redis_data:
  # postgres_data:

networks:
  linkplace-network:
    driver: bridge
